apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/lambda.services.k8s.aws_aliases.yaml
  - bases/lambda.services.k8s.aws_codesigningconfigs.yaml
  - bases/lambda.services.k8s.aws_eventsourcemappings.yaml
  - bases/lambda.services.k8s.aws_functions.yaml
  - bases/lambda.services.k8s.aws_functionurlconfigs.yaml
  - bases/lambda.services.k8s.aws_layerversions.yaml
  - bases/lambda.services.k8s.aws_versions.yaml
