apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - common
resources:
  - bases/lambda.services.k8s.aws_aliases.yaml
  - bases/lambda.services.k8s.aws_codesigningconfigs.yaml
  - bases/lambda.services.k8s.aws_eventsourcemappings.yaml
  - bases/lambda.services.k8s.aws_functions.yaml
  - bases/lambda.services.k8s.aws_functionurlconfigs.yaml
