apiVersion: v1
name: lambda-chart
description: A Helm chart for the ACK service controller for AWS Lambda (lambda)
version: v0.0.0-non-release-version
appVersion: v0.0.0-non-release-version
home: https://github.com/aws-controllers-k8s/lambda-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/lambda-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: lambda Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/lambda-maintainer
keywords:
  - aws
  - kubernetes
  - lambda
